### ISSUE TITLE
[Bug] Blocks replaced with walls, fences and stairs.

### ISSUE THREAD

**Issue by TheJoshBosh** [Treetrain1/Survival-Remastered#11]
**Describe the bug**

A large variety of blocks are replaced with stairs, fences, walls and other placeholder like blocks which makes a lot of things unusable such as rubber trees which don; work due to being different orientations of random logs and having iron fences for leaves

**To Reproduce**

load into a world, dig to find limestone, or go to the nether and it's full of missing blocks, spawn a rubber tree sapling and grow it

**Expected behavior**
What did you expect to happen before finding this bug?

not have placeholding blocks and for rubber trees to give sap.

**Screenshots**

![huge_2022-06-16_18 39 42](https://user-images.githubusercontent.com/107642136/174132900-bd157741-3840-4ad4-8170-fe768ce77071.png)

**Setup:**
 - Operating System [e.g. Windows 10]:windows 11
 - Game Version [e.g. 2.0 Beta 1]:beta 1

**Additional context**
tree sap taps don't work either, I think due to the fact the blocks are acting strangely, even on a tree sap log it doesn't work.

**Comment by EthanRStokes** [comment]
Was this world upgraded from Alpha 2 or 2.1? I can't seem to reproduce it in Beta 1.

**Comment by TheJoshBosh** [comment]
it was a fresh world made and hosted on a server, and the modpack was added by a support employee, ill make a new world and see if that fixes it

**Comment by EthanRStokes** [comment]
I did some playtesting on beta 1 before I released it and it seems fine, but i didnt test when on a server. I'll try to recreate it on the server.

**Comment by TheJoshBosh** [comment]
![huge_2022-06-16_20 19 38](https://user-images.githubusercontent.com/107642136/174148475-8ad0c931-f715-4c8d-99e6-dfcaea9075c4.png)

on a new world still hosted by a server

**Comment by EthanRStokes** [comment]
Just tested it on a server and I'm getting the same results. Something with servers is messed up.

**Comment by EthanRStokes** [comment]
looks like the issue goes back to alpha 2. the issue wasnt happening in alpha 1 and they are pretty similar. i can probably get a fix done soon

**Comment by EthanRStokes** [comment]
pog i have it narrowed down to 10 mods

**Comment by EthanRStokes** [comment]
I believe the Nears mod is causing all this

**Comment by EthanRStokes** [comment]
![image](https://user-images.githubusercontent.com/39657565/174267312-b03c4aec-e125-4a51-9c52-d11e25c7d595.png)
fixed!

**Comment by TheJoshBosh** [comment]
thank you for your time and dedication to your pack!
