### ISSUE TITLE
[Bug] Hammers from Gobber2 crashes the game

### ISSUE THREAD

**Issue by PedroFMBranco** [Treetrain1/Survival-Remastered#12]
When using any Hammer from Gobber2 crashes the game when the target block is a non-solid block from BetterNether.

E.g: Using the End Hammer targeting Red Mold.

**Comment by EthanRStokes** [comment]
i think i fixed it
a fix will be in next release

**Comment by PedroFMBranco** [comment]
quick note, it also seems to happen when targeting other blocks, for example, mushroom block. I'm not sure if your fix will correct the problem globally but I thought it was worth mentioning.
