### ISSUE TITLE
1.19 Beta 2 kick when starting raid. Crash if singleplayer [Bug] 

### ISSUE THREAD

**Issue by JosephBashful** [Treetrain1/Survival-Remastered#14]
**Describe the bug**
i was in Multiplayer with a friend, i had bad omen and was repeately kicked by server when trying to start a raid by entering a Village.
The other player didn't have any problem and the raid didn't start.
The problem still occour in singleplayer, but in that case, was a full crash (here attached)
[crash-2022-07-10_02.30.11-server.txt](https://github.com/Treetrain1/Survival-Remastered/files/9078169/crash-2022-07-10_02.30.11-server.txt)

**To Reproduce**
enter a village with bad omen

**Expected behavior**
normal raid start

**Comment by EthanRStokes** [comment]
I think its been fixed.
the fix will be in beta 3 when it releases
