### ISSUE TITLE
[Feature] Mod suggestions...

### ISSUE THREAD

**Issue by Heus-Sueh** [Treetrain1/Survival-Remastered#22]
### **Describe the feature:**

These mods in my opinion make the game cooler and fun to progress:
[Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Paragliders](https://www.curseforge.com/minecraft/mc-mods/paragliders)

**Comment by EthanRStokes** [comment]
All of those mods are on Forge. I cannot add them.

**Comment by Heus-Sueh** [comment]
If I'm not mistaken the waystone mod is available for fabric too, I just don't know if it has all the functions but these other mods I think are only available in forge.
